language: python
sudo: enabled

env:
        - DEB_CHANGELOG_YML=changelog_md.yml

python:
        - "3.5"
        - "3.6"
        - "3.7"
        - "3.8"

branches:
        only:
        - master
        - develop

before_install:
        - sudo apt-get install python3 python3-yaml python3-pip python3-setproctitle python3-setuptools pylint3 -y
        - sudo apt-get install cdbs debhelper dpkg-dev -y

        - sudo pip3 install pyyaml
        - dpkg -L python3-yaml

        - export PYTHONPATH=$PYTHONPATH:$PWD:/usr/lib/python3/dist-packages:/usr/local/lib/python3/dist-packages
        - export DEB_CHANGELOG_YML=changelog_md.yml

# command to run tests
script:

        - echo "pylint changelog_md.py  ... "
        - pylint3 --errors-only changelog_md.py

        - echo "run changelog_md.py ... "
        - python3 changelog_md.py

        - echo "build package ... "
        - sudo dpkg-buildpackage -uc -us
        - for file in `ls ../debian-changelog-md_*_all.deb`; do sudo dpkg -i $file; done;
