language: python
sudo: enabled

env:
        - DEBIAN_CHANGELOG_YML=changelog-md.yml

python:
        - "2.7"

branches:
        only:
        - master
        - develop

before_install:
        - sudo apt-get install python-yaml python-pip python-setproctitle -y
        - sudo pip install pyyaml
        - sudo dpkg-buildpackage -uc -us
        - for file in `ls ../debian-changelog-md_*_all.deb`; do sudo dpkg -i $file; done;

# command to run tests
script: python changelog-md.py
