language: python
sudo: enabled

env:
        - DEB_CHANGELOG_YML=changelog_md.yml

python:
        - "3.5"
        - "3.6"
        - "3.7"
        - "3.8"

branches:
        only:
        - master
        - develop

before_install:
        - sudo apt-get install python3 python3-yaml python3-pip python3-setproctitle python3-setuptools
        - sudo apt-get install cdbs debhelper dpkg-dev -y
        - sudo dpkg-buildpackage -uc -us
        - for file in `ls ../debian-changelog-md_*_all.deb`; do sudo dpkg -i $file; done;

# command to run tests
script: python3 changelog-md.py
